### ISSUE TITLE
Failed to install on Laravel 6.1

### ISSUE THREAD

**Issue by rliibke** [guiliredu/laravel-seed-migration-estados-cidades-brasil#2]
Hi guys,
I try to install the package on laravel 6.1 and return a error.

Comand line: php ../composer.phar require guiliredu/laravel-seed-migration-estados-cidades-brasil

Response: 
Using version ^1.0 for guiliredu/laravel-seed-migration-estados-cidades-brasil
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install guiliredu/laravel-seed-migration-estados-cidades-brasil 1.0.1
    - Conclusion: remove laravel/framework v6.1.0
    - Installation request for guiliredu/laravel-seed-migration-estados-cidades-brasil ^1.0 -> satisfiable by guiliredu/laravel-seed-migration-estad
    - Conclusion: don't install laravel/framework v6.1.0
    - guiliredu/laravel-seed-migration-estados-cidades-brasil v1.0.0 requires illuminate/support 5.7.* -> satisfiable by illuminate/support[5.7.17,  v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/support 5.7.17|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.7.18|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.7.19|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.0|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.1|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.10|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.11|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.15|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.2|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.20|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.21|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.22|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.23|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.26|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.27|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.28|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.3|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.4|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.5|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.6|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.7|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.8|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.9|don't install laravel/framework v6.1.0
    - Installation request for laravel/framework (locked at v6.1.0, required as ^6.0) -> satisfiable by laravel/framework[v6.1.0].

**Comment by guiliredu** [comment]
Just updated composer.json to use with laravel 6.0
